name: Release

on:
  push:
    branches: [main]

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            pyyaml
      - run: python release_json.py
      - uses: ncipollo/release-action@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: ${{ steps.date.outputs.date }}-${{ github.sha }}
